
// DO NOT EDIT THIS FILE

public class Ads {
  public static final String FACEBOOK_AD = "facebook";
  public static final String TIKTOK_AD = "tiktok";
  public static final String YOUTUBE_AD = "youtube";
  public static final String TV_AD = "tv";
  public static final String INSTAGRAM_AD = "instagram";
}