import java.lang.Math;

// DO NOT EDIT THIS FILE (unless you are working on part 4).

public class Campaign {

  private static final int MAX_PAYOFF = 1;
  private static final int MAX_ADS = 1000 * 1000;

  private static double facebookOdds;
  private static int facebookPayOff;

  private static double tiktokOdds;
  private static int tiktokPayOff;

  private static double youtubeOdds;
  private static int youtubePayOff;

  private static double tvOdds;
  private static int tvPayOff;

  private static double instagramOdds;
  private static int instagramPayOff;

  private static int adsRun;
  private static int adsRemaining;
  private static int totalVotesWon;

  public static void start() {
    facebookOdds = Math.random();
    facebookPayOff = (int) (Math.random()*MAX_PAYOFF+1);

    tiktokOdds = Math.random();
    tiktokPayOff = (int) (Math.random()*MAX_PAYOFF+1);

    youtubeOdds = Math.random();
    youtubePayOff = (int) (Math.random()*MAX_PAYOFF+1);

    tvOdds = Math.random();
    tvPayOff = (int) (Math.random()*MAX_PAYOFF+1);

    instagramOdds = Math.random();
    instagramPayOff = (int) (Math.random()*MAX_PAYOFF+1);

    adsRun = 0;
    adsRemaining = MAX_ADS;
    totalVotesWon = 0;
  }

  public static int runAd(String adType) {
    if (adsRemaining < 0) {
      System.out.println("Sorry, you have used up your ad budget!");
      return 0;
    } 

    if (!adType.equals(Ads.FACEBOOK_AD) &&
        !adType.equals(Ads.TIKTOK_AD) &&
        !adType.equals(Ads.YOUTUBE_AD) &&
        !adType.equals(Ads.TV_AD) &&
        !adType.equals(Ads.INSTAGRAM_AD)) {
      System.out.println("Please pick an add from one of the following:");
      System.out.println(Ads.FACEBOOK_AD);
      System.out.println(Ads.TIKTOK_AD);
      System.out.println(Ads.YOUTUBE_AD);
      System.out.println(Ads.TV_AD);
      System.out.println(Ads.INSTAGRAM_AD);
      return 0;
    }

    int votedReceived = 0;
    double randomNumber = Math.random();

    if (adType.equals(Ads.FACEBOOK_AD) && randomNumber > facebookOdds) {
      votedReceived = facebookPayOff;
    } else if (adType.equals(Ads.TIKTOK_AD) && randomNumber > tiktokOdds) {
      votedReceived = tiktokPayOff;
    } else if (adType.equals(Ads.YOUTUBE_AD) && randomNumber > youtubeOdds) {
      votedReceived = youtubePayOff;
    } else if (adType.equals(Ads.TV_AD) && randomNumber > tvOdds) {
      votedReceived = tvPayOff;
    } else if (adType.equals(Ads.INSTAGRAM_AD) && randomNumber > instagramOdds) {
      votedReceived = instagramPayOff;
    }
    
    --adsRemaining;
    ++adsRun;

    if (votedReceived > 0) {
      totalVotesWon += votedReceived;
    }

    return votedReceived;
  }

  public static void end() {
    System.out.println("Total Votes Won: " + totalVotesWon);
    System.out.println("Total Ads Run: " + adsRun);
    System.out.println("Total Unspent Ads: " + adsRemaining);
    System.out.println("Votes / Ads Run: " + (totalVotesWon*1.0)/adsRun);
  }
}